# TODO: use giner (similar to jinja 2) to make this simpler:
# - don't replicate highly similar services
# - allow variable substitution

version: "3"

services:
  mpi_head:
    build:
        context: ./
        dockerfile: ${BASEDIR}/Dockerfile
        args:
          - BASEDIR=${BASEDIR}
    # image: openmpi
    ports: 
      - "22"
    links: 
      - mpi_node
    networks:
      - net

  mpi_node:
    build:
        context: ./
        dockerfile: ${BASEDIR}/Dockerfile
        args:
          - BASEDIR=${BASEDIR}
    # image: openmpi
    networks:
      - net

# networks:
#   net:
#     driver: bridge